# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190210_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='first_paymnet',
            new_name='first_payment',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='payment_period',
        ),
        migrations.AddField(
            model_name='cost',
            name='next_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='type',
            field=models.CharField(choices=[('el', 'Elementor'), ('sh', 'Server Hosting'), ('do', 'Domains'), ('gs', 'GSuite')], max_length=2),
        ),
    ]
