# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190305_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
