# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_project_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
