# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190306_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='amount_owed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
