# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190301_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='amount_owed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
