# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190306_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='folder_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='folder_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
