# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_client_amount_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
