# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-01 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0005_auto_20190301_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('el', 'Elementor'), ('sh', 'Server Hosting'), ('do', 'Domains'), ('gs', 'GSuite')], max_length=2)),
                ('price', models.PositiveIntegerField()),
                ('client_payment', models.IntegerField()),
                ('last_payment_date', models.DateTimeField()),
                ('payment_period', models.CharField(choices=[('wk', 'Bi-weekly'), ('mo', 'Monthly'), ('an', 'Annualy')], default='wk', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique='True')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
