# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('el', 'Elementor'), ('sh', 'Server Hosting'), ('do', 'Domains'), ('pj', 'Project'), ('pl', 'Plugin'), ('th', 'Theme')], max_length=2)),
                ('price', models.PositiveIntegerField()),
                ('client_payment', models.IntegerField(default=0)),
                ('last_payment_date', models.DateTimeField(auto_now=True)),
                ('payment_period', models.CharField(choices=[('wk', 'Bi-weekly'), ('mo', 'Monthly'), ('an', 'Annualy')], default='wk', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.Cost')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique='True')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
