# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190304_1415'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('el', 'Elementor'), ('sh', 'Server Hosting'), ('do', 'Domains'), ('pj', 'Project'), ('pl', 'Plugin'), ('th', 'Theme')], max_length=2)),
                ('amount', models.IntegerField(default=0)),
                ('last_payment_date', models.DateTimeField(auto_now=True)),
                ('payment_period', models.CharField(choices=[('wk', 'Bi-weekly'), ('mo', 'Monthly'), ('an', 'Annualy')], default='wk', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('el', 'Elementor'), ('sh', 'Server Hosting'), ('do', 'Domains'), ('pj', 'Project'), ('pl', 'Plugin'), ('th', 'Theme')], max_length=2)),
                ('amount', models.IntegerField(default=0)),
                ('last_payment_date', models.DateTimeField(auto_now=True)),
                ('payment_period', models.CharField(choices=[('wk', 'Bi-weekly'), ('mo', 'Monthly'), ('an', 'Annualy')], default='wk', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cost',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='project',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cost',
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
