# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-03 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20190302_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='type',
            field=models.CharField(choices=[('el', 'Elementor'), ('sh', 'Server Hosting'), ('do', 'Domains'), ('ot', 'Other')], max_length=2),
        ),
    ]
