# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-05 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190304_1415'),
        ('financial', '0002_auto_20190304_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.Company'),
            preserve_default=False,
        ),
    ]
