# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_project_amount'),
        ('financial', '0003_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='clientcost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.CostType'),
        ),
        migrations.AlterField(
            model_name='companycost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.CostType'),
        ),
    ]
