# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-03 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_auto_20190303_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='type',
            field=models.CharField(choices=[('el', 'Elementor'), ('sh', 'Server Hosting'), ('do', 'Domains'), ('pj', 'Project'), ('pl', 'Plugin'), ('th', 'Theme')], max_length=2),
        ),
    ]
