# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20190303_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='last_payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
