# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_auto_20190306_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='companycost',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
